# Generated by Django 4.1.2 on 2022-10-31 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_description_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
