# Generated by Django 4.1.2 on 2022-11-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
